#Include %A_ScriptDir%/screens/gimp_open.ahk
#Include %A_ScriptDir%/screens/gimp_canvas_menu_open.ahk
#Include %A_ScriptDir%/screens/gimp_file_export_open.ahk
#Include %A_ScriptDir%/screens/gimp_confirmation_export_modal.ahk
#Include %A_ScriptDir%/screens/gimp_destroy_modal_confirmation.ahk
#Include %A_ScriptDir%/screens/riot_login.ahk
#Include %A_ScriptDir%/screens/riot_login_username_input.ahk
#Include %A_ScriptDir%/screens/riot_login_password_input.ahk
#Include %A_ScriptDir%/screens/riot_lol_play_cta.ahk
#Include %A_ScriptDir%/screens/riot_launch_lol_client.ahk
#Include %A_ScriptDir%/screens/lol_client_popup_email.ahk
#Include %A_ScriptDir%/screens/lol_client_splash_play_button.ahk
#Include %A_ScriptDir%/screens/lol_client_game_mod.ahk
#Include %A_ScriptDir%/screens/lol_client_game_mod_aram.ahk
#Include %A_ScriptDir%/screens/lol_client_aram_lobby.ahk
#Include %A_ScriptDir%/screens/lol_client_aram_in_queue.ahk
#Include %A_ScriptDir%/screens/lol_client_found_aram_game.ahk
#Include %A_ScriptDir%/screens/riot_tos.ahk
#Include %A_ScriptDir%/screens/riot_accept_tos.ahk
#Include %A_ScriptDir%/screens/lol_client_close_dragonland_popup.ahk
#Include %A_ScriptDir%/screens/lol_client_tos.ahk
#Include %A_ScriptDir%/screens/lol_client_accept_tos.ahk
#Include %A_ScriptDir%/screens/lol_client_popup_summoner_icon.ahk
#Include %A_ScriptDir%/screens/lol_client_ranked_popup.ahk
#Include %A_ScriptDir%/screens/lol_client_popup_challenge_tier.ahk
#Include %A_ScriptDir%/screens/riot_ocr.ahk
#Include %A_ScriptDir%/screens/lol_client_tos_ocr.ahk