#Include %A_ScriptDir%/screens/gimp_open.ahk
#Include %A_ScriptDir%/screens/gimp_canvas_menu_open.ahk
#Include %A_ScriptDir%/screens/gimp_file_export_open.ahk
#Include %A_ScriptDir%/screens/gimp_confirmation_export_modal.ahk
#Include %A_ScriptDir%/screens/gimp_destroy_modal_confirmation.ahk
#Include %A_ScriptDir%/screens/riot_login.ahk
#Include %A_ScriptDir%/screens/riot_login_username_input.ahk
#Include %A_ScriptDir%/screens/riot_login_password_input.ahk
#Include %A_ScriptDir%/screens/riot_lol_play_cta.ahk
#Include %A_ScriptDir%/screens/riot_launch_lol_client.ahk